### ISSUE TITLE
REPL mode

### ISSUE THREAD

**Issue by yuppox** [nigelperks/LegacyBasic#2]
Would it be possible to use LegacyBasic in a REPL mode where the user can enter commands or define a program line?

**Comment by nigelperks** [comment]
I have wondered about that. It would need some redesign (1) have a permanent VM (defined in run.c) instead of creating a VM to run a program (2) print errors and continue, instead of errors being fatal. Also I am concerned about feature creep: if there is an immediate mode, it is reasonable to want STOP and CONTINUE to debug an existing program; then new code can be written; then we want a better language, maybe WHILE - WEND or CALL - SUB. But I wanted to focus on running an old program without editing it. Are you thinking of REPL to see what commands do, like python's REPL, or to write new Basic? Or just to have the experience we used to have on micro Basics?

**Comment by yuppox** [comment]
I think errors could still be fatal but maybe there's an angle I'm missing, My goal would be to have an interactive experience, like old 8-bit BASIC editions (and even 16-bit computer BASICs). Ultimately, I would like to be able to have an edit/run mode (as you have now) and an interactive mode.

**Comment by nigelperks** [comment]
Interactive mode now available. Can be improved over time.

**Comment by yuppox** [comment]
Thank you.

**Comment by starsareintherose** [comment]
After doing it, could you consider give a new version tag?

I package it to AUR, see https://aur.archlinux.org/packages/legacybasic
